### ISSUE TITLE
[BE] 서비스가 여러 레포지터리에 의존하는게 나을지 아니면 서비스가 여러 서비스에 의존하는게 나을지

### ISSUE THREAD

**Issue by acs0209** [hobbytrip/hobbytrip#12]
### 📝 Describe

서비스가 여러 테이블의 데이터가 필요하다고 가정
1. 서비스가 여러 레포지터리에 바로 접근해서 데이터 가져오기, 서비스가 여러 레포지터리를 의존
2. 서비스가 다른 서비스에 접근해서 데이터 가져오기, 서비스가 여러 서비스를 의존

둘 중에 어떤 방식이 좋을까요?

### ✅ Tasks

.

**Comment by youcastle03** [comment]
검색을 해보니 둘다 장단점이 많고 편한대로 사용해도 상관없다는 의견이 많은거 같습니다. 둘의 단점을 해결하기 위해 Facade Pattern?을 많이 쓴다는데 이건 어떠신가요??

**Comment by acs0209** [comment]
https://www.inflearn.com/questions/21703/service와-repository의-관계에-대한-질문입니다
위 질문에 대한 좋은 글이 있어 올립니다.

**Comment by HanYoonSoo** [comment]
오 좋은 글 감사합니다!

**Comment by youcastle03** [comment]
감사합니다!!
