### ISSUE TITLE
[FE] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by yeahzee0421** [hobbytrip/hobbytrip#18]
### 🤔 Describe

FE 프로젝트 초기 세팅

### ✅ Tasks

- React
- Vite
- CSS.module
- zustand
- react-router-dom
- react-query
- react-icons
- airbnb JS style guide 적용 + prettier

### 🙋🏻 More
논의되지 않은 npm 설치, 폴더구조 변경은 되도록이면 지양해주세요!

**Comment by yeahzee0421** [comment]
@minhong1126 FE/dev에 초기 설정 마쳤습니다! 깃 특성상 빈 폴더는 커밋이 불가능해서 클론한 뒤에 사진 보고 폴더 구조 만들어주고 작업하면 될 것 같아요
![image](https://github.com/hobbytrip/hobbytrip/assets/107865510/deedc96b-ed4e-42e3-8828-d1794b31a1a8)

**Comment by minhong1126** [comment]
넵넵 확인했습니당

**Comment by minhong1126** [comment]
저희 혹시 store파일은 어떻게 되나요?

**Comment by yeahzee0421** [comment]
store 대신 actions 쓰는게 좋을 것 같아요!

**Comment by minhong1126** [comment]
아항 알겠습니다!!

**Comment by yeahzee0421** [comment]
$npm i zustand
zustand도 설치 부탁드립니다...ㅎㅎ  깜빡하고 빠뜨렸네요ㅠㅠ

**Comment by minhong1126** [comment]
넹넹 알겠습니다!!
