### ISSUE TITLE
[BE] 커뮤니티 서비스 프로젝트 초기 설정 및 기능 구현

### ISSUE THREAD

**Issue by HanYoonSoo** [hobbytrip/hobbytrip#4]
## 작업 대상
- 프로젝트 구조 Init
- 각종 환경설정(Config)
- 각종 예외처리(Exception)
- 각 도메인 엔티티 생성
- 유저 등록
- 서버 생성

## 📄작업 내용

- [x] 공통 예외를 위한 Enum Class Code 구현
- [x] 공통 예외를 위한 GlobalException 구현
 - [x] 각 도메인 Exception은 GlobalException 상속
- [x] Controller로부터 오류를 잡아내는 RestControllerAdvice CommunityExceptionHandler 구현
- [x] AWS S3 관련 환경설정 및 파일 업로드 서비스 구현
- [x] 사용자 요청에 Latency 및 Query 갯수를 로깅하는 LatencyLoggingFilter 구현
- [x] OpenFeign 작업시 오류 처리 세팅 및 로깅을 위한 FeignLoggerConfig, FeignError 구현
- [x] 유저 등록 기능 구현
- [x] 서버 생성 기능 구현
- [x] 각종 Config 및 Component 
- [ ] 서버 생성 시 서버, 카테고리, 채널 상태관리를 위한 카프카 Producer 미구현   
- [ ] AWS S3 버킷 미생성

## 🙋🏻 주의 사항

1. UserServiceFakeClient 사용.
  아직 MSA 환경이 아니므로 UserServiceFakeClient Class 생성 및 활용 했습니다.
2. AWS S3 버킷을 아직 생성하지 않아 관련 부분 임시로 처리했습니다.
3. 과도한/미흡한 Dto 분리, 패키지 나눔, 상속, 추상화가 있는 것 같다면 의견 부탁드립니다.
4. 주석처리 부분은 빼고 봐주시면 감사하겠습니다.

## 레퍼런스

**Comment by acs0209** [comment]
확인했습니다.
