### ISSUE TITLE
[BE] 서비스 디스커버리 역할의 유레카 서버 구현

### ISSUE THREAD

**Issue by HanYoonSoo** [hobbytrip/hobbytrip#9]
## 작업 대상
- 프로젝트 구조 Init
- 유레카 서버 구성
- application.yml

### ✅ Tasks

- [x] @EnableEurekaServer 적용
- [x] EurekaServer의 포트 및 서비스 이름 설정
- [x] 유레카 서버가 유레카 서버에 등록되는 것을 방지하기 위한 application.yml 설정

### 🙋🏻 More

1. EurekaServer의 경우 큰 작업이 필요하지 않습니다.
2. application.yml이 중점이지만, .gitignore로 등록되어 있습니다.

## 레퍼런스

**Comment by youcastle03** [comment]
close issue
